### ISSUE TITLE
Categories, keywords?

### ISSUE THREAD

**Issue by jhollist** [dill/recipes#1]
@dill nice!

As I mentioned, this is been something I've been wanting to do.  Been nice to add categories (i.e. appetizers, desserts, main dish, etc.) and/or keywords.

**Comment by dill** [comment]
Thanks @jhollist!

I think categories of that kind, "courses" if you will, probably makes sense. I'd rather not get too into the weeds with taxonomy.

Perhaps listing dishes under these subcategories on the index page makes sense?

**Comment by dill** [comment]
Went for keywords as this can encapsulate both courses and extra stuff like "Christmas food" or "cake" (technically a dessert, but can be eaten at any time :cake: :+1:)

Done in 428723b.
